wwwApp: DB_SQL Class Reference
DB_SQL Class Reference
Public Member Functions
query ($query, $params=null)
Protected Member Functions
query_params ($query, $params)
query_noparams ($query)
Detailed Description
Definition at line 9 of file sql.php.
Member Function Documentation
DB_SQL::query ($ query, $ params = null)
Definition at line 11 of file sql.php.
Referenced by DB_PostgreSQL::__construct().
        {
                $query = str_replace('table_', TABLE_PREFIX, $query);
                if (func_num_args()>2)
                {
                        $params = func_get_args();
                        array_shift($params);
                }
                if (is_null($params))
                        $result = $this->query_noparams($query);
                else if (is_array($params))
                        $result = $this->query_params($query, $params);
                else
                        $result = $this->query_params($query, array($params));
                if ($result === false)  throw new DbException($errorString);
                $class = 'DBResult_'. $this->driver;
                $this->lastResult = new $class($this, $result);
                return $this->lastResult;
        }
DB_SQL::query_noparams ($ query) [abstract, protected]
Reimplemented in DB_PostgreSQL.
Referenced by query().
DB_SQL::query_params ($ query, $ params) [abstract, protected]
Reimplemented in DB_PostgreSQL.
Referenced by query().
The documentation for this class was generated from the following file:
database/sql.php