wwwApp: Form Class Reference
Form Class Reference
Public Member Functions
__construct ($rows=array(), $action='')
addRow ($row)
offsetGet ($offset)
offsetSet ($offset, $value)
offsetExists ($offset)
offsetUnset ($offset)
getHTML ()
submitted ()
getColumns ()
fetchValues ()
getFormId ()
fetchAndValidateValues ()
assert ($assertion, $errorDescription)
validate (&$value, $validator, $params, $values)
validateCharset ($char, $charset)
Public Attributes
$action = ''
$rows = array()
$values = array()
$cssClass = null
$columnWidth = null
$custom = ''
$submitValue = 'Save'
$valid = false
Detailed Description
Definition at line 8 of file form.php.
Constructor & Destructor Documentation
Form::__construct ($rows = array(), $action = '')
Definition at line 19 of file form.php.
        {
                $this->submitValue = _('Save');
                $this->action = $action;
                foreach ($rows as $id => $row)
                        if (is_int($id))
                                $this->addRow($row); // DEPRECATED, use parseTable to define rows.
                        else
                                $this->rows[$id]= new ArrayObject($row);
        }
Member Function Documentation
Form::addRow ($row)
Definition at line 32 of file form.php.
Referenced by __construct().
        {
                if (!is_array($row))
                        $row = func_get_args();
                $row = arrayToAssoc($row, array('type','name','description','readonly'));
                $this->rows[$row['name']]= new ArrayObject($row);
        }
Form::assert ($assertion, $errorDescription)
Definition at line 158 of file form.php.
        {
                if (!$assertion)
                {
                        global $PAGE;
                        $PAGE->addMessage($errorDescription, 'userError');
                        $this->valid = false;
                }
                return $assertion;
        }
Form::fetchAndValidateValues ()
Definition at line 132 of file form.php.
        {
                global $PAGE;
                $values = $this->fetchValues();
                $this->valid = true;
                foreach ($this->rows as &$row)
                        if (!empty($row['validation']) && empty($row['readonly']))
                {
                        $row['errors'] = array();
                        $validators = explode(',', $row['validation']);
                        foreach ($validators as $v)
{
                                $validator = substr($v, 0, strpos($v.'(', '('));
                                $params = substr($v, strpos($v, '(') + 1, -1);
                                $params = explode(' ', $params);
                                $r = $this->validate($values[$row['name']], $validator, $params, $values);
                                if ($r !== true)
{
                                        $row['errors'][] = $r;
                                        $this->valid = false;
                                }
                        }
                }
                return $values;
        }
Form::fetchValues ()
Definition at line 92 of file form.php.
Referenced by fetchAndValidateValues().
        {
                $values = array();
                foreach ($this->rows as $row)
                {
                        if (!empty($row['readonly'])
                                        || !empty($row['hidden'])
                                        || ($row['type'] == 'checkboxgroup')
                                        || ($row['type'] == 'custom'))
                                continue;
                        $value = isset($_POST[$row['name']]) ? $_POST[$row['name']] : null;
                        if (isset($row['other']) && ($value == VALUE_OTHER))
                                $value = isset($_POST[$row['name'] .'_other']) ? $_POST[$row['name'] .'_other'] : null;
                        switch($row['type'])
{
                                case 'int':
                                        $value = intval($value);
                                        break;
                                case 'timestamp':
                                        $value = strtotime($value);
                                        break;
                                case 'checkbox':
                                        $value = empty($value) ? 0 : 1; // SQL would have problems with true/false.
                                        break;
                        }
                        $values[$row['name']] = $value;
                }
                return $values;
        }
Form::getColumns ()
Definition at line 83 of file form.php.
Referenced by getFormId().
        {
                $columns = array();
                foreach ($this->rows as $row)
                        if (!in_array($row['type'], array('checkboxgroup', 'custom')) && empty($row['notdb']))
                                $columns[]= '"'. $row['name'] .'"';
                return implode(',', $columns);
        }
Form::getFormId ()
Definition at line 127 of file form.php.
Referenced by getHTML(), and submitted().
        {
                return sha1($this->action . $this->getColumns());
        }
Form::getHTML ()
Definition at line 45 of file form.php.
        {
                $params = array(
                        'action'      => $this->action,
                        'class'       => $this->cssClass ? 'class="'. $this->cssClass .'"' : '',
                        'columnWidth' => $this->columnWidth,
                        'custom'      => $this->custom,
                        'submitValue' => $this->submitValue,
                        'formid'      => $this->getFormId(),
                        'rows'        => generateFormRows($this->rows, $this->values),
                );
                $template = new SimpleTemplate($params);
                ?>
                        <form method="post" action="%action%" name="form" %class%>
                                <input type="hidden" name="formid" value="%formid%" />
                                <?php if (is_null($this->columnWidth)) : ?>
                                        <table>
                                <?php else: ?>
                                        <table style="table-layout:fixed">
                                                <tr class="columnWidth"><td width="%columnWidth%"></td></tr>
                                <?php endif; ?>
                                                %rows%
                                        </table>
                                %custom%
                                <?php if (!is_null($this->submitValue)) : ?>
                                        <input type="submit" value="%submitValue%" />
                                <?php endif; ?>
                        </form>
                <?php
                return $template->finish();
        }
Form::offsetExists ($offset)
Definition at line 42 of file form.php.
{ return isset($this->rows[$offset]); }
Form::offsetGet ($offset)
Definition at line 40 of file form.php.
{ return $this->rows[$offset]; }
Form::offsetSet ($offset, $value)
Definition at line 41 of file form.php.
{ $this->rows[$offset] = $value; }
Form::offsetUnset ($offset)
Definition at line 43 of file form.php.
{ unset($this->rows[$offset]); }
Form::submitted ()
Definition at line 77 of file form.php.
        {
                // TODO Could add CSRF protection: just set $_SESSION['requestId'] and check it here.
                return isset($_POST['formid']) && ($_POST['formid'] == $this->getFormId());
        }
Form::validate (& $value, $validator, $params, $values)
Definition at line 169 of file form.php.
Referenced by fetchAndValidateValues().
        {
                global $PAGE;
                switch ($validator)
                {
                        case 'charset':
                                $value = (string) $value;
                                for ($i = 0; $i < mb_strlen($value, 'UTF-8'); $i++)
{
                                        $char = mb_substr($value, $i, 1, 'UTF-8');
                                        $good = false;
                                        foreach ($params as $p)
                                                $good = $good || $this->validateCharset($char, $p);
                                        if (!$good)
                                                return sprintf(_('Invalid character: "%s", position %d.'),
                                                        htmlspecialchars($char),
                                                        $i + 1
                                                );
                                }
                                return true;
                        case 'length':
                                $value = trim($value);
                                if (count($params) == 1)
{
                                        if (strlen($value) != $params[0])
                                                return sprintf(_('The value should have exactly %d characters.'), $params[0]);
                                }
                                else
{
                                        if (strlen($value) < $params[0])
                                                return _('The value is too short'). '(< '. $params[0] ._('characters').').';
                                        if (strlen($value) > $params[1])
                                                return _('The value is too long').  '(> '. $params[0] ._('characters') .').';
                                }
                                return true;
                        case 'email':
                                if (!validEmail($value))
                                        return _('Invalid e-mail address.');
                                return true;
                        case 'equal':
                                if ($value != $values[$params[0]])
                                        return _('The value doesn\'t match it\'s repetition.');
                                unset($values[$params[0]]);
                                return true;
                        case 'int':
                                if (intval($value) != $value)
                                        return _('The value is not an integer.');
                                $value = intval($value);
                                return true;
                        default:
                                return 'Unknown validator: '. $validator .'.';
                }
        }
Form::validateCharset ($char, $charset)
Definition at line 223 of file form.php.
Referenced by validate().
        {
                switch ($charset)
                {
                        case 'alpha':
                                return (bool) preg_match('/(*UTF8)\pL/u', $char);
                        case 'alnum':
                                return $this->validateCharset($char, 'alpha') || $this->validateCharset($char, 'digit');
                        case 'name':
                                return $this->validateCharset($char, 'alpha') || $this->validateCharset($char, ' \'-.’');
                        case 'white':
                                return ctype_space($char);
                        case '':
                                return $char === ' ';
                        default:
                                if (is_callable("ctype_$charset"))
                                return call_user_func_array("ctype_$charset", array($char));
                                return strpos($charset, $char) !== false;
                }
        }
Member Data Documentation
Form::$action = ''
Definition at line 10 of file form.php.
Referenced by __construct().
Form::$columnWidth = null
Definition at line 14 of file form.php.
Form::$cssClass = null
Definition at line 13 of file form.php.
Form::$custom = ''
Definition at line 15 of file form.php.
Form::$rows = array()
Definition at line 11 of file form.php.
Referenced by __construct().
Form::$submitValue = 'Save'
Definition at line 16 of file form.php.
Form::$valid = false
Definition at line 17 of file form.php.
Form::$values = array()
Definition at line 12 of file form.php.
Referenced by fetchAndValidateValues(), fetchValues(), and validate().
The documentation for this class was generated from the following file:
form.php