wwwApp: DB Class Reference
DB Class Reference
Public Member Functions
connect ($connectionString)
last_error ()
& __get ($name)
__call ($name, $args)
num_rows ()
affected_rows ()
fetch ()
fetch_assoc ($n=null)
fetch_all ()
fetch_column ($c=null)
fetch_int ()
fetch_vector ()
Static Public Member Functions
static create ($driver, $connectionString)
Public Attributes
$lastResult = null
$driver
Protected Member Functions
__construct ($connectionString)
Protected Attributes
$tables = array()
Detailed Description
Definition at line 6 of file db.php.
Constructor & Destructor Documentation
DB::__construct ($connectionString) protected
Reimplemented in DB_PostgreSQL.
Definition at line 20 of file db.php.
        {
                if (!$this->connect($connectionString))
                        throw new KnownException(_('Could not connect to database.'). '<br/>
                        <pre>'. $this->last_error() .'</pre>');
        }
Member Function Documentation
DB::__call ($name, $args)
Definition at line 42 of file db.php.
        {
                        return $this->{$name}->offsetGet($args);
        }
& DB::__get ($name)
Definition at line 31 of file db.php.
        {
                $table = TABLE_PREFIX . $name;
                if (isset($this->tables[$table]) && is_object($this->tables[$table]))
                        return $this->tables[$table];
                else
                        throw new KnownException(sprintf(_('Undefined database table <i>%s</i> (prefix is <i>%s</i>).'), $name, TABLE_PREFIX));
        }
DB::affected_rows ()
Definition at line 48 of file db.php.
{ return $this->lastResult->affected_rows(); }
DB::connect ($connectionString) abstract
Reimplemented in DB_PostgreSQL.
Referenced by __construct().
static DB::create ($driver, $connectionString) static
Definition at line 12 of file db.php.
        {
                require_once(strtolower($driver) .'.php');
                $className = "DB_$driver";
                $DB = new $className($connectionString);
                return $DB;
        }
DB::fetch ()
Definition at line 49 of file db.php.
Referenced by DBRow_SQL\count(), and DBTable_PostgreSQL\lastValue().
{ return $this->lastResult->fetch(); }
DB::fetch_all ()
Definition at line 51 of file db.php.
Referenced by DB_PostgreSQL\__construct().
{ return $this->lastResult->fetch_all(); }
DB::fetch_assoc ($n = null)
Definition at line 50 of file db.php.
Referenced by DBRow_SQL\assoc().
{ return $this->lastResult->fetch_assoc($n); }
DB::fetch_column ($c = null)
Definition at line 52 of file db.php.
{ return $this->lastResult->fetch_column($c); }
DB::fetch_int ()
Definition at line 53 of file db.php.
{ return $this->lastResult->fetch_int(); }
DB::fetch_vector ()
Definition at line 54 of file db.php.
{ return $this->lastResult->fetch_vector(); }
DB::last_error () abstract
Reimplemented in DB_PostgreSQL.
Referenced by __construct(), and DB_SQL\query().
DB::num_rows ()
Definition at line 47 of file db.php.
{ return $this->lastResult->count(); }
Member Data Documentation
DB::$driver
Definition at line 9 of file db.php.
Referenced by create(), and DB_SQL\query().
DB::$lastResult = null
Definition at line 8 of file db.php.
Referenced by DB_SQL\query().
DB::$tables = array() protected
Definition at line 10 of file db.php.
Referenced by DB_PostgreSQL\__construct().
The documentation for this class was generated from the following file:
database/db.php