wwwApp: Enum Class Reference
Enum Class Reference
Public Member Functions
offsetGet ($offset)
offsetSet ($offset, $value)
offsetExists ($offset)
exists ($offset)
offsetUnset ($offset)
getIterator ()
assoc ($keyColumn, $valColumn)
Static Public Member Functions
static defineEnum ($enumName, array $items, $default)
static get ($enumName, $keyOrId=null)
Private Member Functions
__construct (array $items, $default)
Private Attributes
$items
$default
Static Private Attributes
static $enumTypes = array()
Detailed Description
Definition at line 8 of file enum.php.
Constructor & Destructor Documentation
Enum::__construct (array $items, $default) private
Definition at line 32 of file enum.php.
        {
                $this->items = array();
                foreach ($items as $key => $item)
                        $this->items[$key]= new EnumItem($item);
                $default['key'] = 'default';
                $default['id']  = -1;
                $this->default = new EnumItem($default);
        }
Member Function Documentation
Enum::assoc ($keyColumn, $valColumn)
Definition at line 54 of file enum.php.
        {
                $a = array();
                foreach ($this->items as $item)
                        $a[$item[$keyColumn]] = $item[$valColumn];
                return $a;
        }
static Enum::defineEnum ($enumName, array $items, $default) static
Definition at line 11 of file enum.php.
        {
                self::$enumTypes[$enumName]= new Enum($items, $default);
                //$function  = 'function enum'. ucfirst($enumName) .'($i=null)';
                //$function .= '{ return Enum::get(\''. $enumName .'\', $i); }';
                //eval($function);
        }
Enum::exists ($offset)
Definition at line 50 of file enum.php.
{ return isset($this->items[$offset]); }
static Enum::get ($enumName, $keyOrId = null) static
Definition at line 19 of file enum.php.
Referenced by enumBlockStatus(), enumBlockType(), enumParticipantStatus(), enumSolutionStatus(), and enumSubject().
        {
                if (is_null($keyOrId))
                        return self::$enumTypes[$enumName];
                if (is_numeric($keyOrId))
                        foreach (self::$enumTypes[$enumName] as $enumItem)
                                if ($enumItem->id == $keyOrId)
                                        return $enumItem;
                return self::$enumTypes[$enumName][$keyOrId];
        }
Enum::getIterator ()
Definition at line 52 of file enum.php.
{ return new ArrayIterator($this->items); }
Enum::offsetExists ($offset)
Definition at line 49 of file enum.php.
{ return isset($this->items[$offset]); }
Enum::offsetGet ($offset)
Definition at line 41 of file enum.php.
        {
                if (isset($this->items[$offset]))
                        return $this->items[$offset];
                else
                        return $this->default;
        }
Enum::offsetSet ($offset, $value)
Definition at line 48 of file enum.php.
{ throw new KnownException('Undefined operation'); }
Enum::offsetUnset ($offset)
Definition at line 51 of file enum.php.
{ throw new KnownException('Undefined operation'); }
Member Data Documentation
Enum::$default private
Definition at line 31 of file enum.php.
Referenced by __construct(), defineEnum(), and offsetGet().
Enum::$enumTypes = array() static private
Definition at line 10 of file enum.php.
Enum::$items private
Definition at line 30 of file enum.php.
The documentation for this class was generated from the following file:
enum.php