wwwApp: DBResult_Postgresql Class Reference
DBResult_Postgresql Class Reference
Public Member Functions
__construct ($DB, $resultResource)
rewind ()
valid ()
key ()
current ()
next ()
count ()
affected_rows ()
fetch_assoc ($n=null)
fetch_vector ($n=null)
fetch_all ()
fetch_column ($column=null)
Public Member Functions inherited from DBResult_SQL
fetch ($n=null)
Public Member Functions inherited from DBResult
fetch_int ()
Protected Attributes
$count = 0
$i = 0
$value = null
Detailed Description
Definition at line 71 of file postgresql.php.
Constructor & Destructor Documentation
DBResult_Postgresql::__construct ($DB, $resultResource)
Reimplemented from DBResult.
Definition at line 77 of file postgresql.php.
        {
                parent::__construct($DB, $resultResource);
                $this->count = $this->count();
        }
Member Function Documentation
DBResult_Postgresql::affected_rows ()
Reimplemented from DBResult_SQL.
Definition at line 106 of file postgresql.php.
{ return pg_affected_rows($this->resultResource); }
DBResult_Postgresql::count ()
Definition at line 105 of file postgresql.php.
Referenced by __construct(), next(), and valid().
{ return pg_num_rows($this->resultResource); }
DBResult_Postgresql::current ()
Definition at line 92 of file postgresql.php.
{ return $this->value; }
DBResult_Postgresql::fetch_all ()
Reimplemented from DBResult.
Definition at line 120 of file postgresql.php.
        {
                $result = pg_fetch_all($this->resultResource);
                // pg_fetch_all returns false for empty results. We should check for errors here.
                if (!$result)  return array();
                return $result;
        }
DBResult_Postgresql::fetch_assoc ($n = null)
Reimplemented from DBResult.
Definition at line 108 of file postgresql.php.
Referenced by next().
        {
                if (is_null($n))  return pg_fetch_assoc($this->resultResource);
                else  return pg_fetch_assoc($this->resultResource, $n);
        }
DBResult_Postgresql::fetch_column ($column = null)
Reimplemented from DBResult.
Definition at line 128 of file postgresql.php.
        {
                if (is_null($column))
                        return pg_fetch_all_columns($this->resultResource);
                else
                        return parent::fetch_column($column);
        }
DBResult_Postgresql::fetch_vector ($n = null)
Reimplemented from DBResult.
Definition at line 114 of file postgresql.php.
        {
                if (is_null($n))  return pg_fetch_row($this->resultResource);
                else  return pg_fetch_row($this->resultResource, $n);
        }
DBResult_Postgresql::key ()
Definition at line 91 of file postgresql.php.
{ return $this->i; }
DBResult_Postgresql::next ()
Definition at line 93 of file postgresql.php.
Referenced by rewind().
        {
                // PostgreSQL stores result resources in a way which
                // doesn't make jumping through rows inefficient
                // (so we're not assuming we can just fetch_assoc() to get the next row by default).
                ++$this->i;
                if ($this->i < $this->count)
                        $this->value = $this->fetch_assoc($this->i);
                else
                        $this->value = null;
        }
DBResult_Postgresql::rewind ()
Definition at line 83 of file postgresql.php.
        {
                // TODO pg_result_seek($this->resultResource, 0); and fetch_assoc()
                // instead of jumping through rows
                $this->i = -1;
                $this->next();
        }
DBResult_Postgresql::valid ()
Definition at line 90 of file postgresql.php.
{ return ($this->i < $this->count); }
Member Data Documentation
DBResult_Postgresql::$count = 0 protected
Definition at line 73 of file postgresql.php.
DBResult_Postgresql::$i = 0 protected
Definition at line 74 of file postgresql.php.
Referenced by key(), and next().
DBResult_Postgresql::$value = null protected
Definition at line 75 of file postgresql.php.
Referenced by current().
The documentation for this class was generated from the following file:
database/postgresql.php