wwwApp: common.php File Reference
common.php File Reference
Variables
$DB = DB::create(DB_DRIVER, DB_CONNECTION_STRING)
Variable Documentation
$DB = DB::create(DB_DRIVER, DB_CONNECTION_STRING)
Definition at line 31 of file common.php.
Referenced by DbException::__construct(), actionAddWorkshopLecturer(), actionAdminUsers(), actionChangePassword(), actionConsiderTutoringApplication(), actionCreateTask(), actionDatabaseRaw(), actionDatabaseTest(), actionDeleteTask(), actionEditAdditionalInfo(), actionEditMotivationLetter(), actionEditOptions(), actionEditOptionsForm(), actionEditProfile(), actionEditSolution(), actionEditTask(), actionEditTasksComment(), actionEditTutoringApplication(), actionEditTutoringApplicationForm(), actionEditUserStatus(), actionEditWorkshop(), actionEditWorkshopLecturers(), actionFetchGmailOAuthAccessToken(), actionHomepage(), actionListArrivalData(), actionListDailyCounts(), actionListPersonalData(), actionListPublicWorkshops(), actionLogin(), actionPasswordReset(), actionRecountSubjectOrder(), actionRegister(), actionRegisterConfirm(), actionRemoveWorkshopLecturer(), actionResignFromWorkshop(), actionShowCorrelation(), actionShowLog(), actionShowPointsTable(), actionShowTaskSolutions(), actionShowWorkshopTasks(), actionSignUpForWorkshop(), actionViewTutoringApplication(), actionViewTutoringApplications(), addUserMenuBox(), applyForCurrentWorkshopEdition(), assertProfileFilled(), buildParticipantList(), buildTaskList(), DB::create(), getName(), getOption(), getUser(), getUserBadge(), getUserHeader(), getUserRoles(), initUser(), insertPermission(), listWorkshops(), logUser(), setVersion(), submitEditWorkshopForm(), and userCan().