wwwApp: email.php File Reference
email.php File Reference
Functions
sendMail ($subject, $content, $to, $isHTML=false)
actionFetchGmailOAuthAccessToken ()
getGoogleOAuthOptions ()
getCurrentUrl ($includeQuery=true)
validEmail ($email)
Function Documentation
actionFetchGmailOAuthAccessToken ()
Definition at line 144 of file email.php.
{
        global $DB, $PAGE;
        if (!userIs('admin'))  throw new PolicyException();
        logUser('redoOAuth');
        $consumer = new Zend_Oauth_Consumer(getGoogleOAuthOptions());
        if (!isset($_SESSION['REQUEST_TOKEN'])) {
                // Get Request Token and redirect to Google
                $scopes = array('https://mail.google.com/');
                $_SESSION['REQUEST_TOKEN'] = serialize($consumer->getRequestToken(array('scope' => implode(' ', $scopes))));
                $consumer->redirect();
        } else {
                // Have Request Token already, Get Access Token
                $requestToken = unserialize($_SESSION['REQUEST_TOKEN']);
                unset($_SESSION['REQUEST_TOKEN']);
                $accessToken = $consumer->getAccessToken($_GET, $requestToken);
                $accessToken = base64_encode(serialize($accessToken));
                $DB->options['gmailOAuthAccessToken']->update(array('value' => $accessToken));
                $PAGE->addMessage("Successfully received accessToken: <pre>$accessToken</pre>", 'success');
                callAction('editOptions');
        }
}
getCurrentUrl ($ includeQuery = true)
Definition at line 185 of file email.php.
Referenced by getGoogleOAuthOptions().
{
  $scheme =  empty($_SERVER['HTTPS']) ? 'http' : 'https';
  $hostname = $_SERVER['SERVER_NAME'];
  $port = $_SERVER['SERVER_PORT'];
  $uri = ($includeQuery) ? $_SERVER['REQUEST_URI'] : $_SERVER['SCRIPT_NAME'];
  if (($port == '80' && $scheme == 'http') || ($port == '443' && $scheme == 'https'))
      $url = $scheme . '://' . $hostname . $uri;
  else
      $url = $scheme . '://' . $hostname . ':' . $port . $uri;
  return $url;
}
getGoogleOAuthOptions ()
Definition at line 167 of file email.php.
Referenced by actionFetchGmailOAuthAccessToken(), and sendMail().
{
        return array(
                'requestScheme' => Zend_Oauth::REQUEST_SCHEME_HEADER,
                'version' => '1.0',
                'consumerKey' => OAUTH_CONSUMER_KEY,
                'signatureMethod' => OAUTH_METHOD,
                'consumerSecret' =>
                        (OAUTH_METHOD == 'RSA-SHA1') ?
                                new Zend_Crypt_Rsa_Key_Private(file_get_contents(OAUTH_CONSUMER_SECRET)) :
                                OAUTH_CONSUMER_SECRET,
                'callbackUrl' => getCurrentUrl(),
                'requestTokenUrl' => 'https://www.google.com/accounts/OAuthGetRequestToken',
                'userAuthorizationUrl' => 'https://www.google.com/accounts/OAuthAuthorizeToken',
                'accessTokenUrl' => 'https://www.google.com/accounts/OAuthGetAccessToken'
        );
}
sendMail ($ subject, $ content, $ to, $ isHTML = false)
Definition at line 53 of file email.php.
Referenced by actionPasswordReset(), actionRegister(), actionReportBugForm(), and errorHandler().
{
        if (EMAIL_METHOD == 'display')
        {
                $message = "
                        Gdyby nie włączone debugowanie, wysłano by maila:<br/>
                        SUBJECT: <i>$subject<i><br/>
                        TO: <i>". json_encode($to) ."</i><br/>
                        CONTENT(html=". json_encode($isHTML) ."):<br/>
                        $content
                ";
                global $PAGE;
                if ($PAGE)
                        $PAGE->addMessage($message);
                else
                        echo $message;
        }
        /*
        // unmaintained (doesn't support $from = array(array('John','a@a'),...))
        else if (EMAIL_METHOD == 'simple')
        {
                if (!$isHTML)
                        $content .= "\n__\nEmail automatycznie wysłany z ". $_SERVER['HTTP_HOST'];
                $from = 'noreply@warsztatywww.nstrefa.pl';
                ini_set("sendmail_from", $from);
                mail($to, "[WWW][app] $subject", $content , "From: $from", "-f$from");
        }
        */
        else if (EMAIL_METHOD == 'gmail')
        {
                $email_address = getOption('gmailOAuthEmail');
                if (!$isHTML)
                        $content .= "\n__\nEmail automatycznie wysłany z ". $_SERVER['HTTP_HOST'];
                $config = new Zend_Oauth_Config();
                $config->setOptions(getGoogleOAuthOptions());
                // Could try-catch here (for 'access disallowed'?)
                $config->setToken(unserialize(base64_decode(getOption('gmailOAuthAccessToken'))));
                $config->setRequestMethod('GET');
                $url = 'https://mail.google.com/mail/b/' . $email_address . '/smtp/';
                $httpUtility = new Zend_Oauth_Http_Utility();
                $params = $httpUtility->assembleParams($url, $config);
                ksort($params);
                $oauthParams = array();
                foreach ($params as $key => $value)
                        if (strpos($key, 'oauth_') === 0)
                                $oauthParams []= $key . '="' . urlencode($value) . '"';
                $initClientRequest = 'GET ' . $url . ' ' . implode(',', $oauthParams);
                $config = array(
                        'ssl' => 'ssl',
                        'port' => '465',
                        'auth' => 'xoauth',
                        'xoauth_request' => base64_encode($initClientRequest)
                );
                $transport = new Zend_Mail_Transport_Smtp('smtp.gmail.com', $config);
                $mail = new Zend_Mail('UTF-8');
                if ($isHTML)  $mail->setBodyHTML($content);
                else          $mail->setBodyText($content);
                $mail->setFrom($email_address, 'Aplikacja WWW');
                if (is_array($to))
                        foreach ($to as $t)
                                $mail->addTo($t[1], $t[0]);
                else  $mail->addTo($to);
                $mail->setSubject("[WWW][app] $subject");
                $mail->send($transport);
                /* If you ever needed to access IMAP this way too: */
                //require_once 'Zend/Mail/Protocol/Imap.php';
                //require_once 'Zend/Mail/Storage/Imap.php';
                /*
                $imap = new Zend_Mail_Protocol_Imap('imap.gmail.com', '993', true);
                $authenticateParams = array('XOAUTH', base64_encode($initClientRequest));
                $imap->requestAndResponse('AUTHENTICATE', $authenticateParams);
                $storage = new Zend_Mail_Storage_Imap($imap);
                echo '<html><head><title>2legged OAuth test</title></head><body>';
                echo '<h1>Total messages: ' . $storage->countMessages() . "</h1>\n";
                echo 'First five messages: <ul>';
                for ($i = 1; $i <= $storage->countMessages() && $i <= 5; $i++ )
                        echo '<li>' . htmlentities($storage->getMessage($i)->subject) . "</li>\n";
                echo '</ul>';
                echo '</body></html>';
                */
        }
}
validEmail ($ email)
Definition at line 201 of file email.php.
Referenced by Form::validate().
{
        $isValid = true;
        $atIndex = strrpos($email, "@");
        if (is_bool($atIndex) && !$atIndex)  return false;
    $domain = substr($email, $atIndex+1);
    $local = substr($email, 0, $atIndex);
    $localLen = strlen($local);
    $domainLen = strlen($domain);
    if ($localLen < 1 || $localLen > 64)  return false;          // local part length exceeded
    if ($domainLen < 1 || $domainLen > 255)  return false; // domain part length exceeded
    if ($local[0] == '.' || $local[$localLen-1] == '.') return false; // local part starts or ends with '.'
    if (preg_match('/\\.\\./', $local))  return false; // local part has two consecutive dots
    if (!preg_match('/^[A-Za-z0-9\\-\\.]+$/', $domain))  return false; // character not valid in domain part
    if (preg_match('/\\.\\./', $domain))  return false; // domain part has two consecutive dots
    if (!preg_match('/^(\\\\.|[A-Za-z0-9!#%&`_=\\/$\'*+?^{}|~.-])+$/',
                 str_replace("\\\\","",$local)))
    {
       // character not valid in local part unless
       // local part is quoted
       if (!preg_match('/^"(\\\\"|[^"])+"$/',
           str_replace("\\\\","",$local)))  return false;
    }
    if (DEBUG<1 && !(checkdnsrr($domain,"MX") ||  checkdnsrr($domain,"A")))  return false; // domain not found in DNS
    return true;
}