wwwApp: enum.php File Reference
enum.php File Reference
Classes
class Enum
class EnumItem
Functions
enumParticipantStatus ($i=null)
enumBlockStatus ($i=null)
enumBlockType ($i=null)
enumSubject ($i=null)
enumSolutionStatus ($i=null)
Function Documentation
enumBlockStatus ($i = null)
Definition at line 104 of file enum.php.
Referenced by actionHomepage(), actionListPublicWorkshops(), actionShowCorrelation(), and submitEditWorkshopForm().
{ return Enum::get('blockStatus', $i); }
enumBlockType ($i = null)
Definition at line 114 of file enum.php.
Referenced by actionEditWorkshop(), actionListPublicWorkshops(), actionShowCorrelation(), actionShowWorkshopTasks(), and submitEditWorkshopForm().
{ return Enum::get('blockType', $i); }
enumParticipantStatus ($i = null)
Definition at line 92 of file enum.php.
Referenced by actionAddWorkshopLecturer(), actionEditSolution(), actionEditUserStatus(), actionHomepage(), actionListOwnWorkshops(), actionResignFromWorkshop(), actionShowCorrelation(), actionShowTaskSolutions(), actionShowWorkshopTasks(), actionSignUpForWorkshop(), buildParticipantList(), buildTaskList(), listWorkshops(), and submitEditWorkshopForm().
{ return Enum::get('participantStatus', $i); }
enumSolutionStatus ($i = null)
Definition at line 139 of file enum.php.
Referenced by actionShowTaskSolutions(), and buildParticipantList().
{ return Enum::get('solutionStatus', $i); }
enumSubject ($i = null)
Definition at line 127 of file enum.php.
Referenced by actionEditWorkshop(), listWorkshops(), and subjectOrder().
{ return Enum::get('subject', $i); }