wwwApp: index.php File Reference
index.php File Reference
Functions
callAction ($action, $args=array(), $redirect=true)
Variables
$PAGE = new Page()
Function Documentation
callAction ($action, $args = array(), $redirect = true)
Calls an action, by default with a 303 redirect - implementing the POST-REDIRECT-GET pattern. The redirect preserves only messages.
Parameters:
$action the action's name, e.g.: 'homepage'.
$args array of arguments past to the action function.
$redirect (optional) Defaults to true. If false, the action will be called directly.
Definition at line 31 of file index.php.
Referenced by actionAddWorkshopLecturer(), actionChangePassword(), actionDeleteTask(), actionEditOptions(), actionEditSolution(), actionEditTask(), actionEditTasksComment(), actionFetchGmailOAuthAccessToken(), actionLogin(), actionRegisterConfirm(), actionRemoveWorkshopLecturer(), actionResignFromWorkshop(), actionSignUpForWorkshop(), applyForCurrentWorkshopEdition(), and submitEditWorkshopForm().
{
        global $PAGE, $USER;
        if ($redirect)
        {
                $_SESSION['pageMessages'] = $PAGE->topContent;
                header('HTTP/1.1 303 See Other');
                $url = 'http://'. $_SERVER['HTTP_HOST'] . ABSOLUTE_PATH_PREFIX;
                if (isset($USER['impersonatedBy']))
                        $url .= 'impersonate('. $USER['uid'] .')/';
                $url .= $action .'('. implode(';', $args) .')';
                header('Location: '. $url);
                exit;
        }
        $action = 'action'. ucfirst($action);
        if (is_callable($action))
                call_user_func_array($action, $args);
        else
                throw new KnownException(_('Unknown action requested.'), '404 Not Found');
}
Variable Documentation
$PAGE = new Page()
 index.php includes pretty much everything and
 calls the appropriate action, parsing the GET.
 The PAGE is built, the action's output written
to $PAGE->content, add*MenuBox()s called.
Definition at line 17 of file index.php.
Referenced by actionAbout(), actionAddWorkshopLecturer(), actionAdminUsers(), actionChangePassword(), actionConsiderTutoringApplication(), actionCreateTask(), actionDatabaseRaw(), actionDatabaseTest(), actionDeleteTask(), actionEditAdditionalInfo(), actionEditMotivationLetter(), actionEditOptions(), actionEditProfile(), actionEditSolution(), actionEditTask(), actionEditTasksComment(), actionEditTutoringApplication(), actionEditTutoringApplicationForm(), actionEditUserStatus(), actionEditWorkshop(), actionEditWorkshopLecturers(), actionFetchGmailOAuthAccessToken(), actionHomepage(), actionListAllWorkshops(), actionListArrivalData(), actionListDailyCounts(), actionListOwnWorkshops(), actionListPersonalData(), actionListPublicWorkshops(), actionLogin(), actionLogout(), actionPasswordReset(), actionRegister(), actionRegisterConfirm(), actionRemoveWorkshopLecturer(), actionReportBug(), actionReportBugForm(), actionResignFromWorkshop(), actionShowCorrelation(), actionShowErrorLog(), actionShowLog(), actionShowPointsTable(), actionShowProfile(), actionShowTaskSolutions(), actionShowWorkshopTasks(), actionSignUpForWorkshop(), actionViewTutoringApplication(), actionViewTutoringApplications(), addAdminMenuBox(), addLoginMenuBox(), addSiteMenuBox(), addTutoringMenuBox(), addUserMenuBox(), addWarsztatyMenuBox(), applyForCurrentWorkshopEdition(), Form\assert(), assertProfileFilled(), buildFormRow(), buildParticipantList(), callAction(), dbg(), Form\fetchAndValidateValues(), getUser(), listWorkshops(), parseUserHTML(), sendMail(), setVersion(), submitEditWorkshopForm(), and Form\validate().