wwwApp: user/password.php File Reference
password.php File Reference
Functions
createPasswordHash ($password)
validatePassword ($password, $correct_hash)
generateRandomPassword ($length)
passwordNeedsRehash ($hash)
slow_equals ($a, $b)
pbkdf2 ($algorithm, $password, $salt, $count, $key_length, $raw_output=false)
Variables
const PBKDF2_HASH_ALGORITHM = "sha512"
const PBKDF2_ITERATIONS = 1000
const PBKDF2_SALT_BYTE_SIZE = 48
const PBKDF2_HASH_BYTE_SIZE = 48
const HASH_SECTIONS = 4
const HASH_ALGORITHM_INDEX = 0
const HASH_ITERATION_INDEX = 1
const HASH_SALT_INDEX = 2
const HASH_PBKDF2_INDEX = 3
Function Documentation
createPasswordHash ($password)
Definition at line 24 of file password.php.
Referenced by actionChangePassword(), actionLogin(), actionPasswordReset(), and actionRegister().
{
        // format: algorithm:iterations:salt:hash
        $salt = base64_encode(mcrypt_create_iv(PBKDF2_SALT_BYTE_SIZE, MCRYPT_DEV_URANDOM));
        return PBKDF2_HASH_ALGORITHM . ":" . PBKDF2_ITERATIONS . ":" .  $salt . ":" .
                base64_encode(pbkdf2(
                        PBKDF2_HASH_ALGORITHM,
                        PASSWORD_SALT . $password,
                        $salt,
                        PBKDF2_ITERATIONS,
                        PBKDF2_HASH_BYTE_SIZE,
                        true
                ));
}
generateRandomPassword ($length)
Definition at line 68 of file password.php.
Referenced by actionPasswordReset().
{
        $random = mcrypt_create_iv(PBKDF2_SALT_BYTE_SIZE, MCRYPT_DEV_URANDOM);
        return substr(sha1(base64_encode($random)), 0, $length);
}
passwordNeedsRehash ($hash)
Definition at line 74 of file password.php.
Referenced by actionLogin().
{
        $params = explode(":", $hash);
        if (count($params) < HASH_SECTIONS)
                return true;
        if ($params[HASH_ALGORITHM_INDEX] === 'old')
                return true;
        return false;
}
pbkdf2 ($algorithm, $password, $salt, $count, $key_length, $raw_output = false)
Definition at line 110 of file password.php.
Referenced by createPasswordHash(), and validatePassword().
{
        $algorithm = strtolower($algorithm);
        if(!in_array($algorithm, hash_algos(), true))
                die('PBKDF2 ERROR: Invalid hash algorithm.');
        if($count <= 0 || $key_length <= 0)
                die('PBKDF2 ERROR: Invalid parameters.');
        $hash_length = strlen(hash($algorithm, "", true));
        $block_count = ceil($key_length / $hash_length);
        $output = "";
        for($i = 1; $i <= $block_count; $i++) {
                // $i encoded as 4 bytes, big endian.
                $last = $salt . pack("N", $i);
                // first iteration
                $last = $xorsum = hash_hmac($algorithm, $last, $password, true);
                // perform the other $count - 1 iterations
                for ($j = 1; $j < $count; $j++) {
                        $xorsum ^= ($last = hash_hmac($algorithm, $last, $password, true));
                }
                $output .= $xorsum;
        }
        if($raw_output)
                return substr($output, 0, $key_length);
        else
                return bin2hex(substr($output, 0, $key_length));
}
slow_equals ($a, $b)
Definition at line 85 of file password.php.
Referenced by validatePassword().
{
        $diff = strlen($a) ^ strlen($b);
        for($i = 0; $i < strlen($a) && $i < strlen($b); $i++)
        {
                $diff |= ord($a[$i]) ^ ord($b[$i]);
        }
        return $diff === 0;
}
validatePassword ($password, $correct_hash)
Definition at line 39 of file password.php.
Referenced by actionChangePassword(), and actionLogin().
{
        // DEPRECATED: The root password is hashed this way so it can be set in config.php,
        // installation scripts only have to write 'rootpassword' instead of a sha1().
        //if ($correct_hash === 'rootpassword')
        //      return slow_equals(ROOT_PASSWORD, $password);
        $params = explode(":", $correct_hash);
        if (count($params) < HASH_SECTIONS)
                return false;
        // DEPRECATED: Accept old passwords
        if ($params[HASH_ALGORITHM_INDEX] === 'old')
                return slow_equals($params[HASH_PBKDF2_INDEX], sha1(OLD_PASSWORD_SALT . $password));
        $pbkdf2 = base64_decode($params[HASH_PBKDF2_INDEX]);
        return slow_equals(
                $pbkdf2,
                pbkdf2(
                        $params[HASH_ALGORITHM_INDEX],
                        PASSWORD_SALT . $password,
                        $params[HASH_SALT_INDEX],
                        (int)$params[HASH_ITERATION_INDEX],
                        strlen($pbkdf2),
                        true
                )
        );
}
Variable Documentation
const HASH_ALGORITHM_INDEX = 0
Definition at line 19 of file password.php.
Referenced by passwordNeedsRehash(), and validatePassword().
const HASH_ITERATION_INDEX = 1
Definition at line 20 of file password.php.
Referenced by validatePassword().
const HASH_PBKDF2_INDEX = 3
Definition at line 22 of file password.php.
Referenced by validatePassword().
const HASH_SALT_INDEX = 2
Definition at line 21 of file password.php.
Referenced by validatePassword().
const HASH_SECTIONS = 4
Definition at line 18 of file password.php.
Referenced by passwordNeedsRehash(), and validatePassword().
const PBKDF2_HASH_ALGORITHM = "sha512"
Definition at line 13 of file password.php.
Referenced by createPasswordHash().
const PBKDF2_HASH_BYTE_SIZE = 48
Definition at line 16 of file password.php.
Referenced by createPasswordHash().
const PBKDF2_ITERATIONS = 1000
Definition at line 14 of file password.php.
Referenced by createPasswordHash().
const PBKDF2_SALT_BYTE_SIZE = 48
Definition at line 15 of file password.php.
Referenced by createPasswordHash(), and generateRandomPassword().