wwwApp: template.php File Reference
template.php File Reference
Classes
class SimpleTemplate
Functions
parseUserHTML ($html)
getTipJS ($tip)
getIcon ($name, $tip=false, $href=false)
getButton ($title, $href, $icon=false)
format ($string)
formatAssoc ($string, $assoc)
alternate ()
buildTableHTML ($rows, $headers=null)
Function Documentation
alternate ()
Definition at line 202 of file template.php.
Referenced by actionViewTutoringApplications(), buildParticipantList(), buildTableHTML(), and buildTaskList().
{
        static $memory = array();
        $args = func_get_args();
        $array = &$memory[serialize($args)];
        if (!isset($array))
                $array = $args;
        while(!(list($key,$val) = each($array)))
                reset($array);
        return $val;
}
buildTableHTML ($rows, $headers = null)
Definition at line 214 of file template.php.
Referenced by actionAdminUsers(), actionListArrivalData(), actionListDailyCounts(), and actionListPersonalData().
{
        echo '<table style="width:auto">';
        if ($headers)
        {
                echo'<thead><tr>';
                foreach ($headers as $h)
                {
                        echo '<th>';
                        if (is_array($h))
{
                                if (!empty($h['order']))
                                        echo '<a href="?order='. htmlspecialchars(urlencode($h['order'])) .'">';
                                echo $h['description'];
                                if (!empty($h['order']))
                                        echo '</a>';
                        }
                        else
                                echo $h;
                        echo '</th>';
                }
                echo '</tr></thead>';
        }
        echo '<tbody>';
        foreach ($rows as $row)
        {
                echo '<tr class="'. alternate('even', 'odd') .'">';
                if ($headers)
                        foreach ($headers as $key => $h)
                                if (array_key_exists($key, $row))
                {
                        echo '<td>'. $row[$key] .'</td>';
                        unset($row[$key]);
                }
                foreach ($row as $key => $value)
                                echo '<td>'. $value .'</td>';
                echo '</tr>';
        }
        echo '</tbody></table>';
}
format ($string)
Definition at line 178 of file template.php.
{
        $args = func_get_args();
        array_shift($args);
        foreach ($args as $i => $arg)
                $string = str_replace('$'. ($i+1), $arg, $string);
        return $string;
}
formatAssoc ($string, $assoc)
Definition at line 189 of file template.php.
Referenced by Page\addMenuBox().
{
        $names = array();
        $values = array();
        foreach ($assoc as $name => $value)
        {
                $names[]= "%$name%";
                $values[]= $value;
        }
        return str_replace($names, $values, $string);
}
getButton ($title, $href, $icon = false)
Definition at line 169 of file template.php.
Referenced by actionShowWorkshopTasks(), actionViewTutoringApplication(), and buildTaskList().
{
        $href = htmlspecialchars($href, ENT_QUOTES);
        $button = $title;
        if ($icon)  $button = getIcon($icon, '') . $button;
        return "<a class='button' href='$href'>$button</a>";
}
getIcon ($name, $tip = false, $href = false)
Definition at line 158 of file template.php.
Referenced by actionViewTutoringApplications(), Page\addMenuBox(), addUserMenuBox(), buildParticipantList(), buildTaskList(), getButton(), and getUserBadge().
{
        $class = strtr($name, '.', '_');
        $js = getTipJS($tip);
        if ($tip===false)  $tip = substr($name,0,-4);
        $icon = "<span class='$class icon' $js></span>";
        //$icon = "<img class='icon' src='images/icons/$name' alt='$title' title='$title'/>";
        if ($href)  $icon = "<a class='iconLink' href='$href'>$icon</a>";
        return $icon;
}
getTipJS ($tip)
Definition at line 151 of file template.php.
Referenced by actionAdminUsers(), actionEditAdditionalInfo(), actionEditProfile(), actionEditUserStatus(), actionShowCorrelation(), actionShowPointsTable(), addUserMenuBox(), buildTaskList(), and getIcon().
{
        if (strlen(trim($tip))==0)  return ' ';
        $tip = htmlspecialchars(addcslashes($tip, "\\\"\n\r"), ENT_QUOTES);     // Tested.
        return " onmouseout='tipoff()' onmouseover='tipon(this,\"$tip\")' ";
}
parseUserHTML ($html)
Definition at line 109 of file template.php.
Referenced by actionDeleteTask(), actionEditSolution(), actionEditUserStatus(), actionShowProfile(), actionShowTaskSolutions(), actionShowWorkshopTasks(), buildFormRow(), and buildTaskList().
{
        // TODO: test prevention of XSS attacks with HTMLPurifier.
        // DEPRECATED: Using mathjax instead, see html.php
        //Parse [tex]code[/tex] into <img src="pathtorenderer.cgi?code"/>.
        /*preg_match_all("#\\[tex\\](.*?)\\[/tex\\]#si",$html,$tex_matches);
        for ($i=0; $i < count($tex_matches[0]); $i++) {
                $pos = strpos($html, $tex_matches[0][$i]); // TODO low: this seems stupid?
                $len = strlen($tex_matches[0][$i]);
                $latex_formula = $tex_matches[1][$i];
                $url = 'http://'. $_SERVER['HTTP_HOST'] . '/cgi-bin/mimetex.cgi?';
                $url .= htmlspecialchars($latex_formula, ENT_QUOTES);
                $img = "<img src='$url' alt='[tex]". htmlspecialchars($latex_formula, ENT_QUOTES) .
                        "[/tex](". _('missing picture'). ")' class='latex' align='absmiddle'/>";
                $html = substr_replace($html, $img, $pos, $len);
        }*/
        // TODO see why TinyMCE includes html-escaped comment tags with MS Word stuff.
        $offset = 0;
        while (($pos = strpos($html, '&lt;!--', $offset)) !== false)
        {
                $end = strpos($html, '--&gt;', $pos+2);
                global $PAGE;
                if ($end === false)
                        $PAGE->addMessage('MSWord copy-paste closing tag not found.', 'exception');
                $end += strlen('--&gt;');
                $html = substr_replace($html, '', $pos, $end-$pos);
                $offset = $pos;
        }
        $config = HTMLPurifier_Config::createDefault();
        $purifier = new HTMLPurifier($config);
        $html = $purifier->purify($html);
        $html = '<span class="userHTML">'. $html .'</span>';
        return $html;
}